---
- hosts: "{{mygroup}}"
  gather_facts: no
  become: yes

  tasks:
  - name: Install PIP packages into Tower's virtualenv
    pip:
      name: "{{ item }}"
      state: latest
      virtualenv_command: /var/lib/awx/venv/ansible/bin/activate
    with_items:
    - bigsuds
    - f5-sdk

  - copy:
      src: f5_inventory.yml
      dest: /tmp/hosts.yml
