---
- hosts: "{{mygroup}}"
  gather_facts: no
  become: yes

  tasks:
  - name: Install PIP packages into Tower's virtualenv
    pip:
      name: f5-sdk
      state: latest
      virtualenv_command: /var/lib/awx/venv/ansible/bin/activate

  - copy:
      src: f5_inventory.yml
      dest: /tmp/hosts.yml
