---
vc_datacenter: 'ONB'
vc_cluster: 'NUC'
vm_name: "{{ HOSTS }}"
vm_type: 'linux'
vm_template: 'rhel-82-base'
vm_annotation: 'Created By Ansible'
vm_wait_for_ip_address: yes
vm_networks:
  - name: "{{ vm_portgroup }}"
    start_connected: yes
vm_disk:
  - size_gb: "{{ vm_disk_size }}"
    autoselect_datastore: True
    datastore:
    - Local01
    - Local02
    - nas01
    - ISO
vm_hardware:
  memory_mb: "{{ vm_ram }}"
  num_cpus: "{{ vm_cpu }}"