---
- name: clone VM
  vmware_guest:
    validate_certs: no
    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    annotation: "{{ vm_annotation }}"
    wait_for_ip_address: "{{ vm_wait_for_ip_address }}"
    networks: "{{ vm_networks }}"
    disk: "{{ vm_disk }}"
    hardware: "{{vm_hardware}}"
    folder: ONB/vm
  register: new_vm

- name: Detect IP address
  add_host:
    name: "{{ new_vm.instance.hw_name }}"
    ansible_host: "{{ new_vm.instance.ipv4 }}"
    groups: vms